#!/usr/bin/env bash
# ================================================================
#  VOIDER — Docker Installer
#  One-command setup for running VOIDER in Docker
#
#  Usage:
#    ./docker-install.sh              # Ollama (local, default)
#    ./docker-install.sh --provider groq --api-key gsk_xxx
#    ./docker-install.sh --provider openai --api-key sk-xxx
#    ./docker-install.sh --provider gemini --api-key AIxx
#    ./docker-install.sh --gpu        # Enable Nvidia GPU for Ollama
#    ./docker-install.sh --pull       # Pull latest image instead of build
# ================================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

print_banner() {
cat << 'EOF'

 ██╗   ██╗ ██████╗ ██╗██████╗ ███████╗██████╗
 ██║   ██║██╔═══██╗██║██╔══██╗██╔════╝██╔══██╗
 ██║   ██║██║   ██║██║██║  ██║█████╗  ██████╔╝
 ╚██╗ ██╔╝██║   ██║██║██║  ██║██╔══╝  ██╔══██╗
  ╚████╔╝ ╚██████╔╝██║██████╔╝███████╗██║  ██║
   ╚═══╝   ╚═════╝ ╚═╝╚═════╝ ╚══════╝╚═╝  ╚═╝

  AI OS Companion — Docker Installer
EOF
}

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

# ── Defaults ────────────────────────────────────────────────
PROVIDER="ollama"
API_KEY=""
MODEL=""
GPU=false
PULL=false
PORT=8000
COMPOSE_FILE="docker-compose.yml"

# ── Argument parsing ────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --provider|-p) PROVIDER="$2"; shift 2 ;;
        --api-key|-k)  API_KEY="$2";  shift 2 ;;
        --model|-m)    MODEL="$2";    shift 2 ;;
        --port)        PORT="$2";     shift 2 ;;
        --gpu)         GPU=true;      shift ;;
        --pull)        PULL=true;     shift ;;
        --help|-h)
            echo "Usage: $0 [--provider ollama|groq|openai|gemini|xai] [--api-key KEY] [--model MODEL] [--port PORT] [--gpu] [--pull]"
            exit 0 ;;
        *) warn "Unknown argument: $1"; shift ;;
    esac
done

print_banner
echo ""

# ── Pre-flight checks ───────────────────────────────────────
info "Checking prerequisites..."

command -v docker &>/dev/null || error "Docker is not installed. Install it from https://docs.docker.com/get-docker/"

DOCKER_COMPOSE_CMD=""
if docker compose version &>/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD="docker compose"
elif command -v docker-compose &>/dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
else
    error "Docker Compose not found. Install it from https://docs.docker.com/compose/install/"
fi
success "Docker and Compose found."

docker info &>/dev/null || error "Docker daemon is not running. Start it with: sudo systemctl start docker"
success "Docker daemon is running."

# ── Provider validation ──────────────────────────────────────
CLOUD_PROVIDERS=("groq" "openai" "gemini" "xai")
NEEDS_KEY=false
for cp in "${CLOUD_PROVIDERS[@]}"; do
    [[ "$PROVIDER" == "$cp" ]] && NEEDS_KEY=true && break
done

if $NEEDS_KEY && [[ -z "$API_KEY" ]]; then
    echo ""
    warn "Provider '${PROVIDER}' requires an API key."
    echo -n "  Enter your ${PROVIDER^^} API key: "
    read -rs API_KEY
    echo ""
    [[ -z "$API_KEY" ]] && error "API key is required for $PROVIDER."
fi

# ── Write .env file ─────────────────────────────────────────
ENV_FILE=".env"
info "Writing $ENV_FILE ..."
cat > "$ENV_FILE" <<ENVEOF
# Generated by docker-install.sh — $(date)
VOIDER_PROVIDER=${PROVIDER}
VOIDER_API_KEY=${API_KEY}
VOIDER_MODEL=${MODEL}
VOIDER_PORT=${PORT}
ENVEOF
success ".env written."

# ── Build or pull image ──────────────────────────────────────
if $PULL; then
    info "Pulling latest VOIDER image from registry..."
    docker pull ghcr.io/ashishdevpandey/voider-ai-os:latest || warn "Registry pull failed; will build locally instead."
    PULL=false
fi

if ! $PULL; then
    info "Building VOIDER Docker image (this may take a few minutes on first run)..."
    docker build \
        -f docker/Dockerfile \
        -t voider-ai-os:latest \
        . && success "Image built successfully."
fi

# ── Compose up ──────────────────────────────────────────────
echo ""
info "Starting VOIDER containers..."

PROFILES="--profile default"
if [[ "$PROVIDER" != "ollama" ]]; then
    # Skip starting Ollama when using cloud provider
    warn "Cloud provider selected ($PROVIDER) — Ollama container will not start."
    PROFILES=""
fi

$DOCKER_COMPOSE_CMD --env-file "$ENV_FILE" $PROFILES up -d

# ── Wait for health ──────────────────────────────────────────
echo ""
info "Waiting for VOIDER to become healthy..."
MAX=60; WAITED=0
until curl -sf "http://localhost:${PORT}/health" &>/dev/null; do
    sleep 3; WAITED=$((WAITED+3))
    if [[ $WAITED -ge $MAX ]]; then
        warn "VOIDER did not become healthy in ${MAX}s."
        warn "Check logs: docker logs voider"
        break
    fi
    echo -n "."
done
echo ""

# ── Done ────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}════════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN}  ✅  VOIDER is running!${RESET}"
echo -e "${BOLD}${GREEN}════════════════════════════════════════${RESET}"
echo ""
echo -e "  🌐 Web UI:   ${CYAN}http://localhost:${PORT}/ui${RESET}"
echo -e "  📡 API:      ${CYAN}http://localhost:${PORT}${RESET}"
echo -e "  📖 API Docs: ${CYAN}http://localhost:${PORT}/docs${RESET}"
echo ""
echo -e "  Provider:    ${BOLD}${PROVIDER}${RESET}"
[[ -n "$MODEL" ]] && echo -e "  Model:       ${BOLD}${MODEL}${RESET}"
echo ""
echo -e "  Useful commands:"
echo -e "    Stop:    ${YELLOW}docker compose down${RESET}"
echo -e "    Restart: ${YELLOW}docker compose restart voider${RESET}"
echo -e "    Logs:    ${YELLOW}docker logs -f voider${RESET}"
echo ""
